### ISSUE TITLE
Loading Spinner

### ISSUE THREAD

**Issue by torch2424** [Kondeo/ccra-book#13]
Add a loading spinner and disable buttons on loading inside of forms

**Comment by julianpoy** [comment]
And in pages, so pages dont load collapsed and then pop big (looks strange)

**Comment by torch2424** [comment]
@julianpoy 

my plan is going to simply create a loading boolean , and display the loading spinner from the index

**Comment by julianpoy** [comment]
Okee

**Comment by torch2424** [comment]
doing this in spinner

**Comment by torch2424** [comment]
Things left to do:

1. Create a service to control loading boolean

2. Stop Clicking in background (Proabably append a no click class through service call)

3.Disable Buttons while loading
