### ISSUE TITLE
Alert users their subscription is ending

### ISSUE THREAD

**Issue by torch2424** [Kondeo/ccra-book#15]
We need to alert users that their subscription is ending if it ends within the week

**Comment by julianpoy** [comment]
This should happen every /login or if they don't re-login, it should happen once. Perhaps store in localStorage alert shown for subscription date?

**Comment by julianpoy** [comment]
Duplicate of #4

**Comment by torch2424** [comment]
closing #4

**Comment by torch2424** [comment]
in retrospect, should of closed this haha

**Comment by torch2424** [comment]
subscription expiry should be ignored for admins

**Comment by torch2424** [comment]
@julianpoy Speaking of admins, is there a boolean being passed with an admin user?

**Comment by torch2424** [comment]
doing this in subAlert
