### ISSUE TITLE
Ping the backend for prices

### ISSUE THREAD

**Issue by torch2424** [Kondeo/ccra-book#16]
we need to grab the current prices of things from the backend before we allow users to click the upgrade button, as it should be displayed to them

**Comment by torch2424** [comment]
What is the route and url for this?

**Comment by torch2424** [comment]
in branch getPrices

**Comment by julianpoy** [comment]
Just GET /prices

**Comment by julianpoy** [comment]
Should return an object with a "new" user price, and a "renew" price.

**Comment by julianpoy** [comment]
http://jnode.ngrok.kondeo.com:8080/prices

**Comment by torch2424** [comment]
:heart:
