### ISSUE TITLE
Search Page

### ISSUE THREAD

**Issue by torch2424** [Kondeo/ccra-book#18]
Create a page that has a simple text input, and has a search button, that will ping the backend for the fuzzy search

below this will be an ng-repeated list, with the results

**Comment by julianpoy** [comment]
I'm going to do this one right? Or were you? I can do it while you do the animations and things if you want :)

**Comment by torch2424** [comment]
If you would like sure, It would help me out a bit. It would be rad if you did #25 before this though. since I remembered you started doing pass word resets right?

**Comment by julianpoy** [comment]
Yes, I am doing both.

**Comment by torch2424** [comment]
Cool sounds good
