### ISSUE TITLE
Cute animations

### ISSUE THREAD

**Issue by julianpoy** [Kondeo/ccra-book#26]
Could you add some fade in animations and a couple shadows here and there? Nothing major, just a few pieces of eyecandy.

**Comment by torch2424** [comment]
in branch cuteAnimations

**Comment by torch2424** [comment]
Angular animate is not applying the classes on ng-if and show/hid like it is supposed too. I am very sad and my head hurts :(

**Comment by torch2424** [comment]
I FOUND THE ANSWER MUAHAHAHAAH https://forum.ionicframework.com/t/angular-animations-nganimate-not-working-for-ionic-v1-2-4-angular-v1-4-3/41107/4

And possibly grunt didnt import css?

https://forum.ionicframework.com/t/is-ng-animate-included/17343

**Comment by julianpoy** [comment]
Please test any animations you do on mobile primarily. This app is going to be used mainly on tablet and phone, so animations cant be too resource-intensive.

**Comment by torch2424** [comment]
Goign to place this on the backburner, after a discussion Julian and I had
