### ISSUE TITLE
Create payment page with Stripe

### ISSUE THREAD

**Issue by julianpoy** [Kondeo/ccra-book#3]
Create a payment page with Stripe.

**Comment by julianpoy** [comment]
@torch2424 If you want to do this actually, you can. Should be pretty easy, if we just use old code from previous stripe CC field implementations.

**Comment by julianpoy** [comment]
I'm officially assigning this to you. Please create a payment page with credit card information with Stripe. Please display this page in the menu pullout on desktop, but not on mobile devices.

**Comment by torch2424** [comment]
Should I be making a credit card looking field? I think the average text fields with min and maxes should suffice, similar to those on paypa and other checkouts

**Comment by julianpoy** [comment]
Just make it nice. Don't worry about it being perfect like our other project, but perhaps reuse some logic for the CC field and validation somesuch.

**Comment by torch2424** [comment]
okay :hamburger:

**Comment by torch2424** [comment]
This will be done in the branch stipePage

**Comment by torch2424** [comment]
So this is a one-time purchase page? Or a page where you enter your information, and then is continually charged?

And I'm gonna have the page like this:

"Description (Which @julianpoy can provide, as he understands how people are being charged better than I do"

First Name
Last Name
Email
CCInfo
Cancel Button
Submit Button

**Comment by torch2424** [comment]
Yo So I finished as much as I could for this page.

Got all the stuff validating and everything, now I am waiting on you to create a route to create users, and update them. That way I can handle error checking and stuff, and also send you the correct payloads. see my latest commit to the branch stripePage

5bd7ec276b0aca875cb945d9b501ee179255f907
