### ISSUE TITLE
Clean Up the code

### ISSUE THREAD

**Issue by torch2424** [Kondeo/ccra-book#31]
Make some services, Put Controllers in their own files, and make it a lot more reable

**Comment by julianpoy** [comment]
Creating a service for all of this that accepts an array of response objects. These objects each have function tied to a status code: 
function success(){}
function conflict(){}
function error(){}

var responseHandlers =  [{ status: 200, success },
   { status: 409, conflict },
    {status: 500, error }]
If a status code occurs that is not listed, the provided service handler will handle it for the user.

**Comment by torch2424** [comment]
in branch cleanUp
