### ISSUE TITLE
No center class

### ISSUE THREAD

**Issue by julianpoy** [Kondeo/ccra-book#38]
There's no center class! I'm lost without it. I tried putting class="center" and nothing happened. Tried debugging a lot of stuff and found out the class simply didn't exist.
What is development without the center class?

**Comment by torch2424** [comment]
I told you!

**Comment by torch2424** [comment]
Im making center.css

**Comment by julianpoy** [comment]
I'll be integrating that in every project.
You know the saying... Without center.css, your project isn't webscale.

**Comment by torch2424** [comment]
For real haha! I'm serious, I still want to make a css library.

Like the amazing https://github.com/daneden/animate.css
