### ISSUE TITLE
Subscription End Alerts

### ISSUE THREAD

**Issue by julianpoy** [Kondeo/ccra-book#41]
CCRA asked that we alert 1 month before and 1 week before.

**Comment by torch2424** [comment]
Okay sounds good!

**Comment by torch2424** [comment]
in branch ccraAlert

**Comment by torch2424** [comment]
So now it will be: every time they login, once in a month, and once in a week

**Comment by torch2424** [comment]
This has been completed in ccraAlert, but Julian is doing backend stuff, so I need to wait for him to finish

**Comment by julianpoy** [comment]
Backend functionality restored.

**Comment by torch2424** [comment]
@julianpoy I would appreciate if you tested this, I shall make a PR, since you have control over the mango rabo and I do not
