### ISSUE TITLE
Search bar should hover

### ISSUE THREAD

**Issue by julianpoy** [Kondeo/ccra-book#43]
Search bar should hover above results when scrolling down

**Comment by torch2424** [comment]
he means a fixed search bar

**Comment by torch2424** [comment]
in branch fixedSearch

**Comment by torch2424** [comment]
Should be finished, waiting on search functionality to test

**Comment by julianpoy** [comment]
Search functionality restored.

**Comment by torch2424** [comment]
testing soon
