### ISSUE TITLE
Fix spacing glitch

### ISSUE THREAD

**Issue by julianpoy** [Kondeo/ccra-book#6]
For some reason we are getting a random spacing glitch. I had some javascript add spacing where it could detect word tags, but it didnt fix it all of the time. This is what it looks like on page1

https://www.dropbox.com/s/4huzhaubaoo17ds/Screenshot%202015-11-13%2000.58.16.png?dl=0

**Comment by torch2424** [comment]
can you please send me the javascript fix? I can simply add it to the java program and re-export again

**Comment by julianpoy** [comment]
`````
// removes MS Office generated guff
function cleanHTML(input) {
  // 1. remove line breaks / Mso classes
  var stringStripper = /(\n|\r| class=(")?Mso[a-zA-Z]+(")?)/g;
  var output = input.replace(stringStripper, ' ');
  // 2. strip Word generated HTML comments
  var commentSripper = new RegExp('<!--(.*?)-->','g');
  var output = output.replace(commentSripper, '');
  var tagStripper = new RegExp('<(/)*(meta|link|span|\\?xml:|st1:|o:|font)(.*?)>','gi');
  // 3. remove tags leave content if any
  output = output.replace(tagStripper, ' ');
  // 4. Remove everything in between and including tags '<style(.)style(.)>'
  var badTags = ['style', 'script','applet','embed','noframes','noscript'];

  for (var i=0; i< badTags.length; i++) {
    tagStripper = new RegExp('<'+badTags[i]+'.*?'+badTags[i]+'(.*?)>', 'gi');
    output = output.replace(tagStripper, '');
  }
  // 5. remove attributes ' style="..."'
  var badAttributes = ['style', 'start'];
  for (var i=0; i< badAttributes.length; i++) {
    var attributeStripper = new RegExp(' ' + badAttributes[i] + '="(.*?)"','gi');
    output = output.replace(attributeStripper, '');
  }
  return output;
}
`````

**Comment by torch2424** [comment]
Could you also send me the fix to the text indent -17px thing you show med?

**Comment by julianpoy** [comment]
Spacing glitch has been resolved via new documents. Please re-export these via your script.
https://www.dropbox.com/s/8sylmnfjifuitk3/2015Compendium_Freelance_FNL_Inside.docx?dl=0
https://www.dropbox.com/s/7jotenlf3r00y1e/2015Compendium_Official_Inside.docx?dl=0

**Comment by torch2424** [comment]
@julianpoy so I no longer need to implement the above code, and this will be all that I need to fix this?

**Comment by torch2424** [comment]
This has been re-exported, please close this issue if all it takes is re-exporting to fix

**Comment by julianpoy** [comment]
The cleanHTML function is something that the backend should implement nomatter what. It removes the stinky formatting of word export, and simplifies it to more standard HTML.

**Comment by torch2424** [comment]
okey

**Comment by torch2424** [comment]
Sent Julian the dropbox link : https://www.dropbox.com/s/zhq0s5vqkhz4fxc/CCRA%20DB.zip?dl=0 closing this
