### ISSUE TITLE
Julian Wants Verison numbering on every request

### ISSUE THREAD

**Issue by torch2424** [Kondeo/ccra-book#67]
This will need an http interceptor

http://www.webdeveasy.com/interceptors-in-angularjs-and-useful-examples/

**Comment by julianpoy** [comment]
Pass me a variable called version

**Comment by torch2424** [comment]
Okay :)

**Comment by torch2424** [comment]
doing this in versionReq

**Comment by torch2424** [comment]
This is only possible on devices, as we cannot grab a version number on web, since web ionic doesnt support cordove

**Comment by julianpoy** [comment]
I think we miscommunicated

**Comment by julianpoy** [comment]
I was speaking of the app version number in package.json

**Comment by torch2424** [comment]
Yeah that's exactly what I am grabbing

**Comment by torch2424** [comment]
Web is a little weird with it

**Comment by julianpoy** [comment]
Why isn't it possible on web?

**Comment by torch2424** [comment]
I found from googling that the best way to do this is using cordova:

https://blog.nraboy.com/2014/11/find-application-version-ionic-framework-app/

https://forum.ionicframework.com/t/how-to-get-app-version-in-ionicframework/12540/2

However, I am sure whipping upa way to access the package.json shouldnt be too difficult for web

**Comment by torch2424** [comment]
Just to let you know too, You asked me to start logging my hours so I have btw

**Comment by julianpoy** [comment]
All you have to do is
```
var package = require("../package.json");
var version = package.version;
```

**Comment by torch2424** [comment]
yeah I figured it out, I got it
