### ISSUE TITLE
Error handling messed up

### ISSUE THREAD

**Issue by julianpoy** [Kondeo/ccra-book#68]
Now, when a session is invalidated the login modal does not pop up, although it gives a message saying session not valid.
Then, if you choose not to login (because the modal never pops up), and try to navigate to a page, the app breaks with an unexpected error 412, presumably since theres no session token being sent (its been deleted)

**Comment by torch2424** [comment]
okay :(

**Comment by torch2424** [comment]
in branch loginModal
