### ISSUE TITLE
Text-indent negative values

### ISSUE THREAD

**Issue by julianpoy** [Kondeo/ccra-book#7]
Text-indent negative values cause some elements to go off of the left of the screen.

https://www.dropbox.com/s/17vcy5he5ekziwe/Screenshot%202015-11-13%2001.24.26.png?dl=0

This is probably a frontend javascript thing with regex (again)

**Comment by torch2424** [comment]
Can you send me the fix to this you showed me in javascript, so I can convert it into java

**Comment by julianpoy** [comment]
https://github.com/Kondeo/ccra-book/blob/master/backend/routes/pages.js
At the bottom of that file

**Comment by torch2424** [comment]
Sent Julian the link for the db: https://www.dropbox.com/s/zhq0s5vqkhz4fxc/CCRA%20DB.zip?dl=0 closing this. For future reference, please make this issues in Kondeo/Word-Document-To-Backend as this refers to improving the backend and the way we are exporting the pages. Not the frontend

**Comment by torch2424** [comment]
Actually updated now here is a better link https://www.dropbox.com/sh/n2g3fz0jskxoqqe/AABe3gx3ceaKf8f1CL8uABlSa?dl=0
