### ISSUE TITLE
Editable pages

### ISSUE THREAD

**Issue by julianpoy** [Kondeo/ccra-book#8]
Please make it so that if an account has a flag editor=true, they can edit pages via an edit link. This will allow us to get into the Apple app store.

**Comment by torch2424** [comment]
Need to check for account status on page load, and not save a cookie telling us if the account is verified. @julianpoy is there a route for this? like one that returns the user

**Comment by torch2424** [comment]
In branch editPage

**Comment by julianpoy** [comment]
I believe so but I'll check.

**Comment by julianpoy** [comment]
I checked this yesterday at home. There is no route. I will build it tonight.

**Comment by torch2424** [comment]
Okay cool!

**Comment by torch2424** [comment]
Yo, I finished this page mostly via 07d39da34b08ace75a31cdafa1d131b7068da532

I am now waiting on you to crate the route, and it needs to be tested. Other than this It has the Meat and potates, now I just need the soda on the side :sunglasses:

**Comment by julianpoy** [comment]
Excellent. I'll craft you a route for this as soon as I can.

**Comment by julianpoy** [comment]
This is indicated via admin=true in the user object.

**Comment by julianpoy** [comment]
Note: Subscription expiry is ignored for admins

**Comment by julianpoy** [comment]
This was added!
